# $OpenXM: OpenXM/src/oxmgraph/Makefile.vc,v 1.1 2009/03/17 17:04:14 ohara Exp $

CFLAGS=-nologo -MT -Ox -I . 
LD=link
LDFLAGS=-nologo

all: oxmgraph.exe

oxmgraph.exe: graph.obj
	$(LD) $(LDFLAGS) -out:$@ $**

clean:
	-@del oxmgraph.exe
	-@del *.obj
