#!/bin/sh
FILES=$*
export FILES
grep sm1_get_Sm1_proc  $FILES 
grep sm1_set_Sm1_proc  $FILES 
grep sm1_find_proc  $FILES 
grep sm1_check_server  $FILES 
grep sm1_start  $FILES 
grep sm1_start_unix  $FILES 
grep sm1_start_windows  $FILES 
grep sm1flush  $FILES 
grep sm1push  $FILES 
grep sm1  $FILES 
grep sm1pop  $FILES 
grep sm1_to_asir_form  $FILES 
grep toAsirForm  $FILES 
grep sm1_toOrdered  $FILES 
grep sm1_toOrdered_dehomo  $FILES 
grep sm1_push_poly0_R  $FILES 
grep sm1_push_poly0  $FILES 
grep sm1_pop_poly0  $FILES 
grep sm1_pop_poly0_0_R  $FILES 
grep sm1_pop_poly0_0  $FILES 
grep sm1_push_int0_R  $FILES 
grep sm1_push_int0  $FILES 
grep sm1_push_0_R  $FILES 
grep sm1_push_0  $FILES 
grep sm1_push  $FILES 
grep sm1_pop  $FILES 
grep sm1_pop2  $FILES 
grep sm1_check_arg_gb  $FILES 
grep sm1_isListOfPoly  $FILES 
grep sm1_isListOfVar  $FILES 
grep sm1_gb  $FILES 
grep sm1_gb_d  $FILES 
grep sm1_pgb  $FILES 
grep sm1_deRham  $FILES 
grep sm1_vlist  $FILES 
grep sm1_ringD  $FILES 
grep sm1_expand_d  $FILES 
grep sm1_mul_d  $FILES 
grep sm1_dehomogenize_d  $FILES 
grep sm1_homogenize_d  $FILES 
grep sm1_groebner_d  $FILES 
grep sm1_reduction_d  $FILES 
grep sm1_reduction_noH_d  $FILES 
grep sm1_hilbert  $FILES 
grep sm1_genericAnn  $FILES 
grep sm1_tensor0  $FILES 
grep sm1_wTensor0  $FILES 
grep sm1_reduction  $FILES 
grep sm1_reduction_noH  $FILES 
grep sm1_xml_tree_to_prefix_string  $FILES 
grep sm1_wbf  $FILES 
grep sm1_wbfRoots  $FILES 
grep sm1_res_div  $FILES 
grep sm1_syz  $FILES 
grep sm1_res_solv  $FILES 
grep sm1_res_solv_h  $FILES 
grep sm1_mul  $FILES 
grep sm1_mul_h  $FILES 
grep sm1_adjoint  $FILES 
grep transpose  $FILES 
grep sm1_resol1  $FILES 
grep sm1_gcd_aux  $FILES 
grep sm1_lcm_aux  $FILES 
grep sm1_mul_v  $FILES 
grep sm1_div_v  $FILES 
grep sm1_rat_to_p_aux  $FILES 
grep sm1_denom_aux0  $FILES 
grep sm1_num_aux0  $FILES 
grep sm1_rat_to_p  $FILES 
grep sm1_distraction  $FILES 
grep sm1_ntoint32  $FILES 
grep sm1_to_ascii_array  $FILES 
grep sm1_from_ascii_array  $FILES 
grep sm1_gkz  $FILES 
grep sm1_appell1  $FILES 
grep sm1aux_dx  $FILES 
grep sm1aux_x  $FILES 
grep sm1_appell4  $FILES 
grep sm1_rank  $FILES 
grep sm1_rrank  $FILES 
grep sm1_auto_reduce  $FILES 
grep sm1_slope  $FILES 
grep sm1_restriction  $FILES 
grep sm1_ahg  $FILES 
grep sm1_bfunction  $FILES 
grep sm1_generalized_bfunction  $FILES 
grep sm1_saturation  $FILES 
:
grep Sm1_proc $FILES
echo "The name sm1pop ... will not be changed."
