#!/bin/sh
# $OpenXM: OpenXM/src/asir-contrib/make-configure,v 1.1 2004/07/02 07:48:47 takayama Exp $
if test ! -f ./.configure_done   -o ! -f ./Makefile
then 
 echo "--prefix=`cd ../../../OpenXM ; pwd`"
 ./configure --prefix="`cd ../../../OpenXM ; pwd`"
else
 echo ".configure_done exists. Do nothing."
fi
touch .configure_done 
