#!/bin/csh
(cd ..; make d0)
set myfile=t.t
set myvar=/home/nobuki/SSkan/Kan/var.sm1
/bin/rm -f $myfile
cat ../incmac.sm1 ../slib.sm1 $myvar  >$myfile

../d0 <../help.k >>$myfile
../d0 <db.k >>$myfile

../d0 <toric0.k >>$myfile

## echo " /bbb [ ] ringd2 def " >>$myfile



