#!/bin/sh
# $OpenXM: OpenXM/src/util/make-configure,v 1.2 2004/06/23 22:49:17 takayama Exp $
if test ! -f ./.configure_done 
then 
# make -f Makefile.conf
 echo "--prefix=`cd ../../../OpenXM ; pwd`"
 ./configure --prefix="`cd ../../../OpenXM ; pwd`"
fi
touch .configure_done 
