#!/bin/sh
# $OpenXM: OpenXM/src/util/make-configure,v 1.3 2004/06/23 23:04:10 takayama Exp $
if test ! -f ./.configure_done   -o ! -f ./Makefile
then 
# make -f Makefile.conf
 echo "--prefix=`cd ../../../OpenXM ; pwd`"
 ./configure --prefix="`cd ../../../OpenXM ; pwd`"
fi
touch .configure_done 
