#!/bin/sh
# $OpenXM: OpenXM/src/util/make-configure,v 1.1 2004/06/14 09:07:32 takayama Exp $
if test ! -f ./.configure_done 
then 
# make -f Makefile.conf
 echo "--prefix=`pwd`/../../../OpenXM"
 ./configure --prefix=`pwd`/../../../OpenXM
fi
touch .configure_done 
