/* $OpenXM: OpenXM/src/util/ox_pathfinder.h,v 1.6 2003/11/16 07:14:11 takayama Exp $ */
char **catArgv(char **argv1,char **argv2);
char *getOStypes();
char *getOpenXM_HOME();
char *getLOAD_SM1_PATH2();
char *getLOAD_K_PATH2(void);
char **getServerEnv(char *oxServer);
char **debugServerEnv(char *oxServer);
char *cygwinPathToWinPath(char *s);
char *winPathToCygwinPath(char *s);
int   oxForkExec(char **argv);
int   oxForkExecBlocked(char **argv);
int ox_pathfinderNoX(int nox);
int ox_pathfinderVerbose(int flag);
char *generateTMPfileName(char *seed);
char *getCppPath(void);
char *getCommandPath(char *cmdname);
char *oxWhich(char *cmdname,char *path);
char *oxWhich_unix(char *cmdname,char *path);
char *oxWhich_win(char *cmdname,char *path);
int oxGetPidList(int *pids,int limit);
