#!/bin/sh
# $OpenXM: OpenXM/src/k097/make-configure,v 1.1 2003/09/02 22:18:40 takayama Exp $
if test ! -f ./.configure_done 
then 
# make -f Makefile.conf
 echo "--prefix=`cd ../../../OpenXM ; pwd`"
 ./configure --prefix="`cd ../../../OpenXM ; pwd`"
fi
touch .configure_done 
