#!/bin/sh
# $OpenXM: OpenXM/src/k097/make-configure,v 1.3 2004/06/30 22:42:33 takayama Exp $
if test ! -f ./.configure_done  -o ! -f ./Makefile
then 
# make -f Makefile.conf
 echo "--prefix=`cd ../../../OpenXM ; pwd`"
 ./configure --prefix="`cd ../../../OpenXM ; pwd`" --enable-shared
fi
touch .configure_done 
