#!/bin/sh
# $OpenXM: OpenXM/src/k097/make-configure,v 1.2 2004/06/24 11:59:22 takayama Exp $
if test ! -f ./.configure_done  -o ! -f ./Makefile
then 
# make -f Makefile.conf
 echo "--prefix=`cd ../../../OpenXM ; pwd`"
 ./configure --prefix="`cd ../../../OpenXM ; pwd`"
fi
touch .configure_done 
