#!/bin/sh
# $OpenXM: OpenXM/src/ox_toolkit/make-configure,v 1.5 2019/01/28 04:51:51 takayama Exp $

prefix=`cd ../..; pwd`
cache_file=`pwd`/config.cache
case "$1" in
"-f"|"--force")
    automake
    autoconf
    touch ${cache_file}
    if [ -z $TARGET_TYPE ]; then 
        ./configure --prefix=${prefix} --with-gmp --cache-file=${cache_file} --enable-shared
    else 
        ./configure --host=${TARGET_TYPE} --prefix=${prefix} --with-gmp --cache-file=${cache_file} --enable-shared
    fi 
    ;;
*)
if [ ! -f ./.configure_done ]; then 
    if [ ! -f ./Makefile.in ]; then 
		automake 
  	fi
    if [ ! -x ./configure ]; then 
		autoconf 
  	fi
    touch ${cache_file}
    if [ -z $TARGET_TYPE ]; then 
        ./configure --prefix=${prefix} --with-gmp --cache-file=${cache_file} --enable-shared
    else 
        ./configure --host=${TARGET_TYPE} --prefix=${prefix} --with-gmp --cache-file=${cache_file} --enable-shared
    fi 
fi
    ;;
esac
touch .configure_done 
