#!/bin/sh
# $OpenXM: OpenXM/src/ox_toolkit/make-configure,v 1.1 2000/02/08 20:34:14 ohara Exp $

case "$1" in
"-f"|"--force")
   automake
   autoconf
   ./configure --prefix="$(cd ../..; pwd)"
   ;;
*)
if [ ! -f ./.configure_done ]; then 
    if [ ! -f ./Makefile.in ]; then 
		automake 
  	fi
    if [ ! -x ./configure ]; then 
		autoconf 
  	fi
    ./configure --prefix="$(cd ../..; pwd)"
fi
    ;;
esac
touch .configure_done 
