#!/bin/sh
# $OpenXM: OpenXM/src/ox_toolkit/make-configure,v 1.3 2004/12/15 12:17:32 ohara Exp $

prefix=`cd ../..; pwd`
cache_file=`pwd`/config.cache
case "$1" in
"-f"|"--force")
    automake
    autoconf
    touch ${cache_file}
    ./configure --prefix=${prefix} --with-gmp --cache-file=${cache_file}
    ;;
*)
if [ ! -f ./.configure_done ]; then 
    if [ ! -f ./Makefile.in ]; then 
		automake 
  	fi
    if [ ! -x ./configure ]; then 
		autoconf 
  	fi
    touch ${cache_file}
    ./configure --prefix=${prefix} --with-gmp --cache-file=${cache_file}
fi
    ;;
esac
touch .configure_done 
