#!/bin/sh
rm -rf ./usr/local/OpenXM/bin/rc.repl
rm -rf ./usr/local/OpenXM/lib/asir-contrib/DO_NOT_EDIT_THIS_DIRECTORY._ALL_FILES_ARE_AUTOMATICDALLY_GENERATED.
#  do not  remove OpenXM/lib/k097/debug
rm -rf ./usr/local/OpenXM/lib/k097/debug/Old/
rm -rf ./usr/local/OpenXM/lib/k097/debug/Old/find-bug
rm -rf ./usr/local/OpenXM/lib/k097/debug/Old/toric0.k.19970310
rm -rf ./usr/local/OpenXM/lib/k097/lib/Old/
rm -rf ./usr/local/OpenXM/lib/k097/lib/Old/printSVector.ccc
rm -rf ./usr/local/OpenXM/lib/k097/lib/Old/setvariables.ccc.96jul23
rm -rf ./usr/local/OpenXM/lib/sm1/DO_NOT_EDIT_THIS_DIRECTORY._ALL_FILES_ARE_COPIED_FROM_kan96xx_Doc
rm -rf ./usr/local/OpenXM/lib/sm1/Old/
rm -rf ./usr/local/OpenXM/lib/sm1/Old/bfunc.sm1
rm -rf ./usr/local/OpenXM/lib/sm1/Old/bf.sm1
rm -rf ./usr/local/OpenXM/lib/sm1/Old/int-d.sm1
rm -rf ./usr/local/OpenXM/lib/sm1/Old/cv2.sm1
rm -rf ./usr/local/OpenXM/lib/sm1/Old/int-q.sm1
rm -rf ./usr/local/OpenXM/lib/sm1/Old/int.sm1
rm -rf ./usr/local/OpenXM/lib/sm1/factor-a.sm1.org
rm -rf ./usr/local/OpenXM/lib/sm1/ole
rm -rf ./usr/local/OpenXM/lib/sm1/ox-win_old.sm1
rm -rf ./usr/local/OpenXM/lib/sm1/oxasir-win_old.sm1
rm -rf ./usr/local/OpenXM/lib/sm1/oxasir_old.sm1
rm -rf ./usr/local/OpenXM/lib/sm1/oxk0_old.sm1
rm -rf ./usr/local/OpenXM/lib/sm1/r-interface.sm1.org
rm -rf ./usr/local/OpenXM/lib/sm1/restall_s.sm1.org
rm -rf ./usr/local/OpenXM/lib/sm1/restall_s.sm1.org2
# HTML manuals are removed. See /usr/local/OpenXM/doc/kan96xx
rm -rf ./usr/local/OpenXM/lib/sm1/ttt
rm -rf ./usr/local/OpenXM/lib/sm1/onlinehelp
##
rm -rf ./usr/local/OpenXM/lib/asir/asir_key
#
rm -rf ./usr/local/OpenXM/rc/kde/
rm -rf ./usr/local/OpenXM/rc/kde/asir-knoppix
rm -rf ./usr/local/OpenXM/rc/kde/asir-openxm
rm -rf ./usr/local/OpenXM/rc/kde/asir-openxm-knoppix
rm -rf ./usr/local/OpenXM/rc/kde/openxm-binary-knoppix
rm -rf ./usr/local/OpenXM/rc/kde/sm1
#
rm -rf ./usr/local/OpenXM/doc/platform-ja.txt
# ./usr/local/OpenXM/doc/OpenXM-spec is kept.
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/ERRATA.html
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/Makefile
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/Makefile-intro
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/OpenXM-RFC.html
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/anonymous.html
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/cmotag.h
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/hopo_std_color.xpm
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/hopo_std_gray.png
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/hopo_std_gray.xpm
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/index-binary.html
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/index-doc.html
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/index-packages.html
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/index.html
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/install-faq.txt
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/logo-openxm2-color.xpm
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/logo-openxm2.bmp
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/logo-openxm2.jpg
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/logo-openxm2.png
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/logo-openxm2.xpm
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/logo-openxm5.bmp
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/logo-openxm5.jpg
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/logo-openxm_simple0.bmp
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/logo-openxm_simple0.jpg
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/oxMessageTag.h
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/people.html
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/smCommand.h
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/top.html
rm -rf ./usr/local/OpenXM/doc/OpenXM-web/version.c
# papers will be removed
rm -rf ./usr/local/OpenXM/doc/Papers/
rm -rf ./usr/local/OpenXM/doc/Papers/bfct.tex
rm -rf ./usr/local/OpenXM/doc/Papers/3k.ps
rm -rf ./usr/local/OpenXM/doc/Papers/cl2emult.cls
rm -rf ./usr/local/OpenXM/doc/Papers/blen.ps
rm -rf ./usr/local/OpenXM/doc/Papers/cropmark.sty
rm -rf ./usr/local/OpenXM/doc/Papers/genkou19991125.tex
rm -rf ./usr/local/OpenXM/doc/Papers/job-pool.asir
rm -rf ./usr/local/OpenXM/doc/Papers/jsiam-noro.tex
rm -rf ./usr/local/OpenXM/doc/Papers/jsiamb-noro.tex
rm -rf ./usr/local/OpenXM/doc/Papers/jssac.sty
rm -rf ./usr/local/OpenXM/doc/Papers/math.sty
rm -rf ./usr/local/OpenXM/doc/Papers/ohp-metro.tex
rm -rf ./usr/local/OpenXM/doc/Papers/ohp-v-minimal.tex
rm -rf ./usr/local/OpenXM/doc/Papers/ohp19991125.tex
rm -rf ./usr/local/OpenXM/doc/Papers/ohp20001220.tex
rm -rf ./usr/local/OpenXM/doc/Papers/ox_math_interruption.tex
rm -rf ./usr/local/OpenXM/doc/Papers/rgb.sty
rm -rf ./usr/local/OpenXM/doc/Papers/rims-2002-12-12-ja-ohp.tex
rm -rf ./usr/local/OpenXM/doc/Papers/rims-2002-12-12-ja.tex
rm -rf ./usr/local/OpenXM/doc/Papers/rims-2002-noro-ja.tex
rm -rf ./usr/local/OpenXM/doc/Papers/rims-2003-12-16-ja-ohp.tex
rm -rf ./usr/local/OpenXM/doc/Papers/rims-2003-12-16-sq.eps
rm -rf ./usr/local/OpenXM/doc/Papers/rims-2003-12-16-sq2.eps
rm -rf ./usr/local/OpenXM/doc/Papers/rims2000-tmp-ja.tex
rm -rf ./usr/local/OpenXM/doc/Papers/rims2000.tex
rm -rf ./usr/local/OpenXM/doc/Papers/rims2001-noro.tex
rm -rf ./usr/local/OpenXM/doc/Papers/rims2002-noro.tex
rm -rf ./usr/local/OpenXM/doc/Papers/rims2003-noro-ohp.tex
rm -rf ./usr/local/OpenXM/doc/Papers/rims2003-noro.tex
rm -rf ./usr/local/OpenXM/doc/Papers/sprmindx.sty
rm -rf ./usr/local/OpenXM/doc/Papers/subeqnar.sty
rm -rf ./usr/local/OpenXM/doc/ascm2001/
rm -rf ./usr/local/OpenXM/doc/ascm2001/Makefile
rm -rf ./usr/local/OpenXM/doc/ascm2001/README
rm -rf ./usr/local/OpenXM/doc/ascm2001/acmconf.cls
rm -rf ./usr/local/OpenXM/doc/ascm2001/ascm2001.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001/bib.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001/data-format.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001/design-outline.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001/flushend.sty
rm -rf ./usr/local/OpenXM/doc/ascm2001/heterotic-network.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001/homogeneous-network.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001/katsura7.ps
rm -rf ./usr/local/OpenXM/doc/ascm2001/openxm-clients.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001/openxm-development-environment.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001/openxm-servers.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001/openxm-stackmachines.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001/ox-messages.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001/reset.eps
rm -rf ./usr/local/OpenXM/doc/ascm2001/session-management.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001/speedup.ps
rm -rf ./usr/local/OpenXM/doc/ascm2001p/
rm -rf ./usr/local/OpenXM/doc/ascm2001p/acmconf.cls
rm -rf ./usr/local/OpenXM/doc/ascm2001p/README
rm -rf ./usr/local/OpenXM/doc/ascm2001p/ascm2001.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001p/bib.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001p/cz.ps
rm -rf ./usr/local/OpenXM/doc/ascm2001p/data-format.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001p/demo.rr
rm -rf ./usr/local/OpenXM/doc/ascm2001p/design-outline.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001p/flushend.sty
rm -rf ./usr/local/OpenXM/doc/ascm2001p/heterotic-network.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001p/homogeneous-network.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001p/katsura7.ps
rm -rf ./usr/local/OpenXM/doc/ascm2001p/ohp-ja.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001p/ohp.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001p/openxm-clients.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001p/openxm-development-environment.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001p/openxm-servers.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001p/openxm-stackmachines.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001p/ox-messages.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001p/reset.eps
rm -rf ./usr/local/OpenXM/doc/ascm2001p/session-management.tex
rm -rf ./usr/local/OpenXM/doc/ascm2001p/speedup.ps
rm -rf ./usr/local/OpenXM/doc/ascm2001p/sprocl.sty
rm -rf ./usr/local/OpenXM/doc/ascm2001p/sprocl.tex
rm -rf ./usr/local/OpenXM/doc/calc2000/
rm -rf ./usr/local/OpenXM/doc/calc2000/behringer1.sty
rm -rf ./usr/local/OpenXM/doc/calc2000/bib.tex
rm -rf ./usr/local/OpenXM/doc/calc2000/calc2000.tex
rm -rf ./usr/local/OpenXM/doc/calc2000/data-format.tex
rm -rf ./usr/local/OpenXM/doc/calc2000/design-outline.tex
rm -rf ./usr/local/OpenXM/doc/calc2000/flushend.sty
rm -rf ./usr/local/OpenXM/doc/calc2000/heterotic-network.tex
rm -rf ./usr/local/OpenXM/doc/calc2000/homogeneous-network.tex
rm -rf ./usr/local/OpenXM/doc/calc2000/katsura7.ps
rm -rf ./usr/local/OpenXM/doc/calc2000/openxm-clients.tex
rm -rf ./usr/local/OpenXM/doc/calc2000/openxm-development-environment.tex
rm -rf ./usr/local/OpenXM/doc/calc2000/openxm-stackmachines.tex
rm -rf ./usr/local/OpenXM/doc/calc2000/ox-messages.tex
rm -rf ./usr/local/OpenXM/doc/calc2000/reset.eps
rm -rf ./usr/local/OpenXM/doc/calc2000/session-management.tex
rm -rf ./usr/local/OpenXM/doc/calc2000/speedup.ps
rm -rf ./usr/local/OpenXM/doc/calc2000p/
rm -rf ./usr/local/OpenXM/doc/calc2000p/calc2000.tex
rm -rf ./usr/local/OpenXM/doc/calc2000p/3k.ps
rm -rf ./usr/local/OpenXM/doc/calc2000p/behringer1.sty
rm -rf ./usr/local/OpenXM/doc/calc2000p/client.tex
rm -rf ./usr/local/OpenXM/doc/calc2000p/efficient.tex
rm -rf ./usr/local/OpenXM/doc/calc2000p/func1.tex
rm -rf ./usr/local/OpenXM/doc/calc2000p/func2.tex
rm -rf ./usr/local/OpenXM/doc/calc2000p/reliable.tex
rm -rf ./usr/local/OpenXM/doc/calc2000p/rgb.sty
## Remove algorithmic descriptions
rm -rf ./usr/local/OpenXM/doc/compalg/
rm -rf ./usr/local/OpenXM/doc/compalg/appgr.tex
rm -rf ./usr/local/OpenXM/doc/compalg/all.tex
rm -rf ./usr/local/OpenXM/doc/compalg/effgr.tex
rm -rf ./usr/local/OpenXM/doc/compalg/bib.tex
rm -rf ./usr/local/OpenXM/doc/compalg/ps/
rm -rf ./usr/local/OpenXM/doc/compalg/ps/blenall.ps
rm -rf ./usr/local/OpenXM/doc/compalg/ps/0.ps
rm -rf ./usr/local/OpenXM/doc/compalg/ps/0d.ps
rm -rf ./usr/local/OpenXM/doc/compalg/ps/1.ps
rm -rf ./usr/local/OpenXM/doc/compalg/ps/1d.ps
rm -rf ./usr/local/OpenXM/doc/compalg/ps/2.ps
rm -rf ./usr/local/OpenXM/doc/compalg/ps/2d.ps
rm -rf ./usr/local/OpenXM/doc/compalg/ps/4.ps
rm -rf ./usr/local/OpenXM/doc/compalg/ps/4d.ps
rm -rf ./usr/local/OpenXM/doc/compalg/ps/cross.ps
rm -rf ./usr/local/OpenXM/doc/compalg/factor.tex
rm -rf ./usr/local/OpenXM/doc/compalg/fglm.tex
rm -rf ./usr/local/OpenXM/doc/compalg/gcd.tex
rm -rf ./usr/local/OpenXM/doc/compalg/gr.tex
rm -rf ./usr/local/OpenXM/doc/compalg/intro.tex
rm -rf ./usr/local/OpenXM/doc/compalg/my.sty
rm -rf ./usr/local/OpenXM/doc/compalg/num.tex
rm -rf ./usr/local/OpenXM/doc/compalg/poly.tex
rm -rf ./usr/local/OpenXM/doc/compalg/prdec.tex
rm -rf ./usr/local/OpenXM/doc/histrical-doc/
rm -rf ./usr/local/OpenXM/doc/histrical-doc/install.oxweave.199912xx
rm -rf ./usr/local/OpenXM/doc/issac2000/
rm -rf ./usr/local/OpenXM/doc/issac2000/acmconf.cls
rm -rf ./usr/local/OpenXM/doc/issac2000/README
rm -rf ./usr/local/OpenXM/doc/issac2000/flushend.sty
rm -rf ./usr/local/OpenXM/doc/issac2000/bib.tex
rm -rf ./usr/local/OpenXM/doc/issac2000/data-format.tex
rm -rf ./usr/local/OpenXM/doc/issac2000/design-outline.tex
rm -rf ./usr/local/OpenXM/doc/issac2000/heterotic-network.tex
rm -rf ./usr/local/OpenXM/doc/issac2000/homogeneous-network.tex
rm -rf ./usr/local/OpenXM/doc/issac2000/issac2000.ps
rm -rf ./usr/local/OpenXM/doc/issac2000/issac2000.tex
rm -rf ./usr/local/OpenXM/doc/issac2000/katsura7.ps
rm -rf ./usr/local/OpenXM/doc/issac2000/openxm-clients.tex
rm -rf ./usr/local/OpenXM/doc/issac2000/openxm-development-environment.tex
rm -rf ./usr/local/OpenXM/doc/issac2000/openxm-stackmachines.tex
rm -rf ./usr/local/OpenXM/doc/issac2000/ox-messages.tex
rm -rf ./usr/local/OpenXM/doc/issac2000/reset.eps
rm -rf ./usr/local/OpenXM/doc/issac2000/session-management.tex
rm -rf ./usr/local/OpenXM/doc/issac2000/speedup.ps
##  ./usr/local/OpenXM/doc/oxlib/ is kept.
##  ./usr/local/OpenXM/doc/ox_toolkit/ is kept
##  ./usr/local/OpenXM/doc/ox_math/ is kept
##  ./usr/local/OpenXM/doc/asir2000/ is kept
##  ./usr/local/OpenXM/doc/kan96xx/ is kept
##  ./usr/local/OpenXM/doc/asir-contrib/ is kept
#
rm -rf ./usr/share/info/
rm -rf ./usr/share/info/gmp.info-2.gz
rm -rf ./usr/share/info/gmp.info-3.gz
rm -rf ./usr/share/info/gmp.info.gz
rm -rf ./usr/share/info/gmp.info-1.gz
#
rm -rf ./usr/local/OpenXM/rc/repl
