RSYNC=rsync -Cavz

usage:

rsync: rsync-gsl-t-1 rsync-so3
rsync-gsl-t-1: 
	${RSYNC} ../../hgm/gsl-t-1/src/*.c hgm/src/
	${RSYNC} ../../hgm/gsl-t-1/src/*.h hgm/src/
rsync-so3:
	${RSYNC} ../../hgm/so3/src/*.c hgm/src/

