# $OpenXM$

OX_web_other=/home/web/OpenXM/Current/doc/other-docs
usage:
	@echo "targets: usage install"

oxgen-index: oxgen-index.c
install: oxgen-index
	cp oxgen-index cron-other-docs.sh os_muldif-get.sh ${OX_web_other}

