#!/bin/sh
# $OpenXM: OpenXM/src/ox_pari/make-configure,v 1.1 2016/09/22 10:20:30 ohara Exp $

prefix=`cd ../..; pwd`
cache_file=`pwd`/config.cache
case "$1" in
"-f"|"--force")
    automake
    autoconf
    touch ${cache_file}
    ./configure --prefix=${prefix} --cache-file=${cache_file}
    ;;
"-d"|"--disable-shared")
if [ ! -f ./.configure_done ]; then 
    if [ ! -f ./Makefile.in ]; then 
		automake 
  	fi
    if [ ! -x ./configure ]; then 
		autoconf 
  	fi
    touch ${cache_file}
    ./configure --prefix=${prefix} --cache-file=${cache_file} --disable-shared
fi
;;
*)
if [ ! -f ./.configure_done ]; then 
    if [ ! -f ./Makefile.in ]; then 
		automake 
  	fi
    if [ ! -x ./configure ]; then 
		autoconf 
  	fi
    touch ${cache_file}
    ./configure --prefix=${prefix} --cache-file=${cache_file}
fi
    ;;
esac
touch .configure_done 
