#!/bin/sh
# $OpenXM: OpenXM/src/ox_pari/make-configure,v 1.2 2016/09/23 03:04:22 takayama Exp $

prefix=`cd ../..; pwd`
cache_file=`pwd`/config.cache
case "$1" in
"-f"|"--force")
    automake
    autoconf
    touch ${cache_file}
    if [ -z $TARGET_TYPE ]; then
        ./configure --prefix=${prefix} --cache-file=${cache_file}
    else
        ./configure --host=${TARGET_TYPE} --prefix=${prefix} --cache-file=${cache_file}
    fi
    ;;
"-d"|"--disable-shared")
if [ ! -f ./.configure_done ]; then 
    if [ ! -f ./Makefile.in ]; then 
		automake 
  	fi
    if [ ! -x ./configure ]; then 
		autoconf 
  	fi
    touch ${cache_file}
    if [ -z $TARGET_TYPE ]; then
        ./configure --prefix=${prefix} --cache-file=${cache_file} --disable-shared
    else
        ./configure --host=${TARGET_TYPE} --prefix=${prefix} --cache-file=${cache_file} --disable-shared
    fi
fi
;;
*)
if [ ! -f ./.configure_done ]; then 
    if [ ! -f ./Makefile.in ]; then 
		automake 
  	fi
    if [ ! -x ./configure ]; then 
		autoconf 
  	fi
    touch ${cache_file}
    if [ -z $TARGET_TYPE ]; then
        ./configure --prefix=${prefix} --cache-file=${cache_file}
    else
        ./configure --host=${TARGET_TYPE} --prefix=${prefix} --cache-file=${cache_file}
    fi
fi
    ;;
esac
touch .configure_done 
