% $OpenXM$
\JP \input jtexinfo
\EG \input texinfo
@iftex
@catcode`@#=6
@def@fref#1{@xrefX[#1,,@code{#1},,,]}
\JP @def@b#1{{@bf@gt #1}}
\EG @def@b#1{{@bf #1}}
@catcode`@#=@other
@end iftex
@overfullrule=0pt
@c -*-texinfo-*-
@comment %**start of header
@setfilename omproxyman
@settitle OMproxy
@comment %**end of header
@comment %@setchapternewpage odd

@ifinfo
@macro fref{name}
\JP @ref{\name\,,@code{\name\}}
\EG @ref{\name\,,@code{\name\}}
@end macro
@end ifinfo

@iftex
@comment @finalout
@end iftex

@titlepage

@title OMproxy
@subtitle OMproxy User's Manual
\\\ @subtitle Edition 4.1 for Asir-991214
@subtitle January 2000

@author  by Y. Tamura
\B\\
@page
@vskip 0pt plus 1filll
Copyright @copyright{} FUJITSU LABORATORIES LIMITED.
1994-1999. All rights reserved.
\E
@end titlepage

@synindex vr fn

@comment  node-name,  next,  previous,  up
@node Top,, (dir), (dir)

@menu
* OMproxy::
@end menu

@include omproxy.texi

\B\\
@node 索引,,, Top
@unnumbered 索引
\E
\B\\
@node Index,,, Top
@unnumbered Index
\E
\\@printindex fn
\\@printindex cp
@iftex
@vfill @eject
@end iftex
\\\@summarycontents
@contents
@bye
