@comment $OpenXM$

@node OMproxy,,, Top
@unnumbered OMproxy

@menu
\JP * 形式::
\JP * 機能説明::
\JP * オプション::
\JP * 変換規則::
@end menu

\JP @node 形式,,, OMproxy
\JP @section 形式

java OMproxy [options]


\JP @node 機能説明,,, OMproxy
\JP @section 機能説明

\BJP
OpenXM で規定されている CMO 形式のオブジェクトと,
OpenMath 規約の ML 表現で表現されたオブジェクトとの相互変換を行なう.
この OMproxy 自体, OpenXM で規定されたサーバスタックマシンとなっている.
\E


\JP @node スタックマシンコマンド,,, OMproxy
\JP @section スタックマシンコマンド

現在実装されているスタックマシンコマンドは以下である.

@subsection SM_popCMO

@subsection SM_mathcap

@subsection SM_executeFunction
\BJP
スタックからデータを取り出し, サーバのローカル関数を実行する.
用意されている関数はローカル関数の節を参照.
\E


\JP @node ローカル関数,,, OMproxy
\JP @section ローカル関数

@subsection CMO2OMXML
\BJP
CMO 形式を OpenMath 規約の XML 表現に変換する.
\E

@subsection OMXML2CMO
\BJP
OpenMath 規約の XML 表現を CMO 形式に変換する.
\E


\JP @node オプション,,, OMproxy
\JP @section オプション


@subsection -h
\JP 簡単な使用法の出力を行なう.
\EG show easy help.

@subsection -host hostname
\BJP
接続を行なうポートの指定を行なう. デフォルトは localhost.
\E

@subsection -data port
\BJP
接続を行なうデータポート番号の指定を行なう.
指定がなければ 1300 となる.
\E

@subsection -control port
\BJP
接続を行なうコントロールポート番号の指定を行なう.
指定がなければ 1300 となる.
\E

\\\         -insecure       this version ignore this option


\JP @node 変換規則,,, OMproxy
\JP @section 変換規則


\JP @node バグ,,, OMproxy
\JP @section バグ

@itemize
\BJP
@item   reverse connection は実装されていない.
\E
@end itemize
