# $OpenXM: OpenXM/rc/bashrc,v 1.14 2007/11/27 22:26:29 takayama Exp $
OpenXM_HOME=$HOME/OpenXM
export OpenXM_HOME
PATH=$OpenXM_HOME/bin:$PATH
ASIR_LIBDIR=$OpenXM_HOME/lib/asir
export ASIR_LIBDIR
ASIRLOADPATH=$OpenXM_HOME/src/asir-contrib/packages/src:$OpenXM_HOME/src/asir-contrib/packages/sample:$OpenXM_HOME/lib/asir-contrib:.
export ASIRLOADPATH
ASIR_CONFIG=$OpenXM_HOME/rc/asirrc
export ASIR_CONFIG
if [ "$ASIR_RSH" = "" ]; then
ASIR_RSH='ssh -f -X -A '
export ASIR_RSH
fi
LOAD_SM1_PATH=$OpenXM_HOME/lib/sm1
export LOAD_SM1_PATH
LOAD_K_PATH=$OpenXM_HOME/lib/k097
export LOAD_K_PATH
OX_XTERM_SCROLL=2000
export OX_XTERM_SCROLL
if test $LD_LIBRARY_PATH ; then
  LD_LIBRARY_PATH=$OpenXM_HOME/lib:$LD_LIBRARY_PATH  ;
else
  LD_LIBRARY_PATH=$OpenXM_HOME/lib ;
fi
export LD_LIBRARY_PATH
# for MacOS
if test $DYLD_LIBRARY_PATH ; then
  DYLD_LIBRARY_PATH=$OpenXM_HOME/lib:$DYLD_LIBRARY_PATH  ;
else
  DYLD_LIBRARY_PATH=$OpenXM_HOME/lib ;
fi
export DYLD_LIBRARY_PATH


