# $OpenXM: OpenXM/rc/cshrc,v 1.4 1999/11/13 01:53:22 takayama Exp $
setenv OpenXM_HOME $HOME/OpenXM
set path=($OpenXM_HOME/bin $path)
rehash
setenv ASIR_LIBDIR $OpenXM_HOME/lib/asir
setenv ASIRLOADPATH ASIRLOADPATH=$OpenXM_HOME/src/asir-contrib/packages/src:$OpenXM_HOME/src/asir-contrib/packages/sample:.
setenv LOAD_SM1_PATH $OpenXM_HOME/lib/sm1
setenv LOAD_K_PATH   $OpenXM_HOME/lib/k097

