# $OpenXM: OpenXM/rc/cshrc,v 1.6 2000/01/16 22:04:39 takayama Exp $
setenv OpenXM_HOME $HOME/OpenXM
set path=($OpenXM_HOME/bin $path)
rehash
setenv ASIR_LIBDIR $OpenXM_HOME/lib/asir
setenv ASIRLOADPATH $OpenXM_HOME/src/asir-contrib/packages/src:$OpenXM_HOME/src/asir-contrib/packages/sample:$OpenXM_HOME/lib/asir-contrib:.
setenv LOAD_SM1_PATH $OpenXM_HOME/lib/sm1
setenv LOAD_K_PATH   $OpenXM_HOME/lib/k097

