#!/bin/sh
# $OpenXM: OpenXM/rc/gen-shell-scripts,v 1.5 2000/03/04 11:03:36 takayama Exp $

#asir
	rm -f asir
	echo "#!/bin/csh" >asir
	cat dot.cshrc >>asir
	echo 'exec $OpenXM_HOME/bin/fep $OpenXM_HOME/bin/asir $*' >>asir
	chmod +x asir

#sm1
	rm -f sm1
	echo "#!/bin/csh" >sm1
	cat dot.cshrc >>sm1
	echo 'exec $OpenXM_HOME/bin/fep $OpenXM_HOME/bin/sm1 $*' >>sm1
	chmod +x sm1

#gp
	rm -f oxgp
	echo "#!/bin/csh" >oxgp
	cat dot.cshrc >>oxgp
	echo 'exec $OpenXM_HOME/bin/gp $*' >>oxgp
	chmod +x oxgp

#oxmath
	rm -f oxmath
	echo "#!/bin/csh" >oxmath
	cat dot.cshrc >>oxmath
	echo 'exec $OpenXM_HOME/bin/fep math $*' >>oxmath
	chmod +x oxmath

#oxMathematica
	rm -f oxMathematica
	echo "#!/bin/csh" >oxMathematica
	cat dot.cshrc >>oxMathematica
	echo 'exec Mathematica  $*' >>oxMathematica
	chmod +x oxMathematica

#ox  (launcher of kxx)
	rm -f ox
	echo "#!/bin/csh" >ox
	cat dot.cshrc >>ox
	echo 'exec $OpenXM_HOME/bin/ox $*' >>ox
	chmod +x ox
