#!/bin/sh
# $OpenXM: OpenXM/rc/gen-shell-scripts,v 1.13 2004/06/21 06:06:15 takayama Exp $

# openxm
	rm -f openxm
	echo "#!/bin/sh" >openxm
	cat dot.bashrc >>openxm
	cat inst-feprc.sh >>openxm
	echo 'exec $*' >>openxm
	chmod +x openxm

#asir
	rm -f asir
	echo "#!/bin/sh" >asir
	cat dot.bashrc >>asir
#	echo 'exec $OpenXM_HOME/bin/fep $OpenXM_HOME/bin/asir $*' >>asir
	echo 'exec $OpenXM_HOME/bin/asir $*' >>asir
	chmod +x asir

#webasir
	rm -f webasir
	echo "#!/bin/sh" >webasir
	cat dot.bashrc >>webasir
	echo 'exec $OpenXM_HOME/bin/sm1 -s "[(parse) (httpd-asir.sm1) pushfile] extension ; asirweb " ' >>webasir
	chmod +x webasir

#sm1
	rm -f sm1
	echo "#!/bin/sh" >sm1
	cat dot.bashrc >>sm1
#	echo 'exec $OpenXM_HOME/bin/fep $OpenXM_HOME/bin/sm1 $*' >>sm1
	echo 'exec $OpenXM_HOME/bin/sm1 $*' >>sm1
	chmod +x sm1

#gp
#	rm -f oxgp
#	echo "#!/bin/sh" >oxgp
#	cat dot.bashrc >>oxgp
#	echo 'exec $OpenXM_HOME/bin/gp $*' >>oxgp
#	chmod +x oxgp

#oxmath
	rm -f oxmath
	echo "#!/bin/sh" >oxmath
	cat dot.bashrc >>oxmath
#	echo 'exec $OpenXM_HOME/bin/fep math $*' >>oxmath
	echo 'exec math $*' >>oxmath
	chmod +x oxmath

#oxMathematica
	rm -f oxMathematica
	echo "#!/bin/sh" >oxMathematica
	cat dot.bashrc >>oxMathematica
	echo 'exec Mathematica  $*' >>oxMathematica
	chmod +x oxMathematica

#ox  (launcher of kxx)
	rm -f ox
	echo "#!/bin/sh" >ox
	cat dot.bashrc >>ox
	echo 'exec $OpenXM_HOME/bin/ox $*' >>ox
	chmod +x ox
