#!/bin/sh
# $OpenXM: OpenXM/rc/make-ssh-environment,v 1.1 2000/10/10 04:51:19 ohara Exp $

. "`dirname $0`/dot.bashrc"
# touch $HOME/.ssh/environment
set | egrep '^(PATH|OpenXM_HOME|ASIR_LIBDIR|ASIRLOADPATH|ASIR_CONFIG|ASIR_RSH|LOAD_SM1_PATH|LOAD_K_PATH|LD_LIBRARY_PATH)=' >> $HOME/.ssh/environment
