#!/bin/sh
# $OpenXM$

. "`dirname $0`/bashrc"
# touch $HOME/.ssh/environment
set | egrep '^(PATH|OpenXM_HOME|ASIR_LIBDIR|ASIRLOADPATH|ASIR_CONFIG|ASIR_RSH|LOAD_SM1_PATH|LOAD_K_PATH|LD_LIBRARY_PATH)=' >> $HOME/.ssh/environment
