.C $OpenXM$
.TH OPENXM 1 "5 March 2000"
.SH NAME
openxm \-  A shell script to start binaries under OpenXM/bin
.SH SYNOPSIS
.B openxm
.RB [ args ] 

.SH DESCRIPTION
The shell script openxm starts binaries under OpenXM/bin
with an appropriate setting of environmental variables.
OpenXM is a project to build a free, or open source infrastracture
for mathematical softwares.
The OpenXM package is a collection of mathematical softwares that
support the OpenXM protocol for mathematics.
It includes servers that support the OpenXM protocol.


.SH USE
.TP
.B openxm asir
to start OpenXM/bin/asir (Risa/asir with OpenXM support).
.TP
.B openxm sm1
to start OpenXM/bin/sm1.
.TP
.B openxm oxmath
to start OpenXM/bin/oxmath  (Mathematica with OpenXM support).

.TP
.B REMARK
For each main client under OpenXM/bin like asir, a shell script
for that client is installed under /usr/local/bin.
For instance, "openxm fep asir" is equivalent to "/usr/local/bin/asir".

.SH MANUALS
See /usr/local/OpenXM/doc/

.SH FILES
.TP
.I /usr/local/OpenXM
main directory


.SH PRIMARY FTP SITE
The most recent distributions can be found at
.RS
.I http://www.math.sci.kobe-u.ac.jp/OpenXM
.RE
This cite will be moved to
.RS
.I http://www.openxm.org
.RE
in a future.



.SH AUTHORS
See OpenXM/Copyright.

.SH SEE ALSO
.IR asir (1),
.IR sm1 (1),

.SH COPYING
Most part of the OpenXM package follows a BSD-like copyright.
See the COPYRIGHT file in the
distribution OpenXM/Copyright.
