#!/bin/sh
# $OpenXM: OpenXM/src/kan96xx/make-configure,v 1.1 2004/06/24 12:45:15 takayama Exp $
if test ! -f ./.configure_done   -o ! -f ./Makefile
then 
# make -f Makefile.conf
 echo "--prefix=`cd ../../../OpenXM ; pwd`"
 ./configure --prefix="`cd ../../../OpenXM ; pwd`"
fi
touch .configure_done 
