#!/bin/sh
# $OpenXM: OpenXM/src/ox_math/make-configure,v 1.2 2002/08/15 02:31:52 ohara Exp $

if [ ! -f ./.configure_done ]; then
	case `uname` in
    CYGWIN*)
        cp -f Makefile.cygwin Makefile
        (cd mathlink; sh ./configure-cygwin)
        ;;
    *)
        if [ ! -x ./configure ]; then
    		autoconf
      	fi
        ./configure
    	;;
    esac
fi
touch .configure_done
