@comment $OpenXM: OpenXM/src/asir-doc/parts/builtin.texi,v 1.2 1999/12/21 02:47:31 noro Exp $
\BJP
@node 組み込み函数,,, Top
@chapter 組み込み函数
\E
\BEG
@node Built-in Function,,, Top 
@chapter Built-in Function
\E

@menu
\BJP
* 数の演算::
* bit 演算::
* 多項式および有理式の演算::
* 一変数多項式の演算::
* リストの演算::
* 配列::
* 構造体::
* 型を求める函数::
* 函数に対する操作::
* 文字列に関する演算::
* 入出力::
* その他::
\E
\BEG
* Numbers::
* Bit operations::
* Polynomials and rational expressions::
* Univariate polynomials::
* Lists::
* Arrays::
* Structures::
* Types:: 
* Operations on functions::
* Strings:: 
* Inputs and Outputs::
* Miscellaneouses::
\E
@end menu

@include parts/builtin/num.texi
@include parts/builtin/bit.texi
@include parts/builtin/poly.texi
@include parts/builtin/upoly.texi
@include parts/builtin/list.texi
@include parts/builtin/array.texi
@include parts/builtin/structure.texi
@include parts/builtin/type.texi
@include parts/builtin/function.texi
@include parts/builtin/string.texi
@include parts/builtin/io.texi
@include parts/builtin/misc.texi

