#!/bin/sh
# $OpenXM: OpenXM/src/kxx/make-configure,v 1.5 2000/12/21 08:20:10 takayama Exp $
if test ! -f ./.configure_done 
then 
# make -f Makefile.conf
 echo "--prefix=`cd ../../../OpenXM ; pwd`"
 ./configure --prefix="`cd ../../../OpenXM ; pwd`"
fi
touch .configure_done 
