#! /bin/sh
# $OpenXM: OpenXM/src/k097/lib/restriction/bench2,v 1.1 2001/01/26 12:42:56 takayama Exp $
# How to execute?
#   unsetenv DISPLAY   ( do not forget for oxc.)
#   nohup ./bench2 &

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(4,5);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(4,6);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(4,7);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(4,8);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(4,9);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(4,10);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(5,6);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(5,7);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(5,8);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(5,9);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(5,10);
quit;
EOF


