#! /bin/sh
# $OpenXM$

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(4,5);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(4,6);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(4,7);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(4,8);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(4,9);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(4,10);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(5,6);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(5,7);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(5,8);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(5,9);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
nonquasi2(5,10);
quit;
EOF


