#! /bin/sh
# $OpenXM$

k0 <<EOF
NoX=true;
load("demo.k");;
DeRham2WithAsir(P2[0]);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
DeRham2WithAsir(P2[1]);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
DeRham2WithAsir(P2[2]);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
DeRham2WithAsir(P2[3]);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
DeRham2WithAsir(P2[4]);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
DeRham2WithAsir(P2[5]);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
DeRham3WithAsir(P3[0]);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
DeRham3WithAsir(P3[1]);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
DeRham3WithAsir(P3[2]);
quit;
EOF

k0 <<EOF
NoX=true;
load("demo.k");;
DeRham3WithAsir(P3[3]);
quit;
EOF


