#!/bin/tcsh

set K0_HOME=/home/nobuki/SSWork/yacc
set SM1_HOME=/home/nobuki/SSkan/Kan
echo "$HOME/bin/d0 will be used for compiling."
/bin/rm -f $1.tmp $1.ksm1 
$HOME/bin/d0 <$1 >$1.tmp
echo "/K00_verbose 0 def " >$1.ksm1
cat $K0_HOME/incmac.sm1 >>$1.ksm1
cat $SM1_HOME/var.sm1 >>$1.ksm1
cat $K0_HOME/slib.sm1 >>$1.ksm1

## aux files from startup.k
$HOME/bin/d0 <$K0_HOME/help.k >>$1.ksm1

cat $1.tmp >>$1.ksm1
/bin/rm -f $1.tmp
echo "$1.ksm1 is generated."
