#define SnullSnull 0
#define SnullSinteger 1
#define SnullSstring 2
#define SnullSexecutableArray 3
#define SnullSoperator 4
#define SnullSdollar 5
#define SnullSarray 6
#define SnullSleftBraceTag 7
#define SnullSrightBraceTag 8
#define SnullSpoly 9
#define SnullSarrayOfPOLY 10
#define SnullSmatrixOfPOLY 11
#define SnullSlist 12
#define SnullSfile 13
#define SnullSring 14
#define SnullSuniversalNumber 15
#define SnullSrationalFunction 16
#define SnullSclass 17
#define SnullSdouble 18
#define SnullSbyteArray 19
#define SintegerSnull 20
#define SintegerSinteger 21
#define SintegerSstring 22
#define SintegerSexecutableArray 23
#define SintegerSoperator 24
#define SintegerSdollar 25
#define SintegerSarray 26
#define SintegerSleftBraceTag 27
#define SintegerSrightBraceTag 28
#define SintegerSpoly 29
#define SintegerSarrayOfPOLY 30
#define SintegerSmatrixOfPOLY 31
#define SintegerSlist 32
#define SintegerSfile 33
#define SintegerSring 34
#define SintegerSuniversalNumber 35
#define SintegerSrationalFunction 36
#define SintegerSclass 37
#define SintegerSdouble 38
#define SintegerSbyteArray 39
#define SstringSnull 40
#define SstringSinteger 41
#define SstringSstring 42
#define SstringSexecutableArray 43
#define SstringSoperator 44
#define SstringSdollar 45
#define SstringSarray 46
#define SstringSleftBraceTag 47
#define SstringSrightBraceTag 48
#define SstringSpoly 49
#define SstringSarrayOfPOLY 50
#define SstringSmatrixOfPOLY 51
#define SstringSlist 52
#define SstringSfile 53
#define SstringSring 54
#define SstringSuniversalNumber 55
#define SstringSrationalFunction 56
#define SstringSclass 57
#define SstringSdouble 58
#define SstringSbyteArray 59
#define SexecutableArraySnull 60
#define SexecutableArraySinteger 61
#define SexecutableArraySstring 62
#define SexecutableArraySexecutableArray 63
#define SexecutableArraySoperator 64
#define SexecutableArraySdollar 65
#define SexecutableArraySarray 66
#define SexecutableArraySleftBraceTag 67
#define SexecutableArraySrightBraceTag 68
#define SexecutableArraySpoly 69
#define SexecutableArraySarrayOfPOLY 70
#define SexecutableArraySmatrixOfPOLY 71
#define SexecutableArraySlist 72
#define SexecutableArraySfile 73
#define SexecutableArraySring 74
#define SexecutableArraySuniversalNumber 75
#define SexecutableArraySrationalFunction 76
#define SexecutableArraySclass 77
#define SexecutableArraySdouble 78
#define SexecutableArraySbyteArray 79
#define SoperatorSnull 80
#define SoperatorSinteger 81
#define SoperatorSstring 82
#define SoperatorSexecutableArray 83
#define SoperatorSoperator 84
#define SoperatorSdollar 85
#define SoperatorSarray 86
#define SoperatorSleftBraceTag 87
#define SoperatorSrightBraceTag 88
#define SoperatorSpoly 89
#define SoperatorSarrayOfPOLY 90
#define SoperatorSmatrixOfPOLY 91
#define SoperatorSlist 92
#define SoperatorSfile 93
#define SoperatorSring 94
#define SoperatorSuniversalNumber 95
#define SoperatorSrationalFunction 96
#define SoperatorSclass 97
#define SoperatorSdouble 98
#define SoperatorSbyteArray 99
#define SdollarSnull 100
#define SdollarSinteger 101
#define SdollarSstring 102
#define SdollarSexecutableArray 103
#define SdollarSoperator 104
#define SdollarSdollar 105
#define SdollarSarray 106
#define SdollarSleftBraceTag 107
#define SdollarSrightBraceTag 108
#define SdollarSpoly 109
#define SdollarSarrayOfPOLY 110
#define SdollarSmatrixOfPOLY 111
#define SdollarSlist 112
#define SdollarSfile 113
#define SdollarSring 114
#define SdollarSuniversalNumber 115
#define SdollarSrationalFunction 116
#define SdollarSclass 117
#define SdollarSdouble 118
#define SdollarSbyteArray 119
#define SarraySnull 120
#define SarraySinteger 121
#define SarraySstring 122
#define SarraySexecutableArray 123
#define SarraySoperator 124
#define SarraySdollar 125
#define SarraySarray 126
#define SarraySleftBraceTag 127
#define SarraySrightBraceTag 128
#define SarraySpoly 129
#define SarraySarrayOfPOLY 130
#define SarraySmatrixOfPOLY 131
#define SarraySlist 132
#define SarraySfile 133
#define SarraySring 134
#define SarraySuniversalNumber 135
#define SarraySrationalFunction 136
#define SarraySclass 137
#define SarraySdouble 138
#define SarraySbyteArray 139
#define SleftBraceTagSnull 140
#define SleftBraceTagSinteger 141
#define SleftBraceTagSstring 142
#define SleftBraceTagSexecutableArray 143
#define SleftBraceTagSoperator 144
#define SleftBraceTagSdollar 145
#define SleftBraceTagSarray 146
#define SleftBraceTagSleftBraceTag 147
#define SleftBraceTagSrightBraceTag 148
#define SleftBraceTagSpoly 149
#define SleftBraceTagSarrayOfPOLY 150
#define SleftBraceTagSmatrixOfPOLY 151
#define SleftBraceTagSlist 152
#define SleftBraceTagSfile 153
#define SleftBraceTagSring 154
#define SleftBraceTagSuniversalNumber 155
#define SleftBraceTagSrationalFunction 156
#define SleftBraceTagSclass 157
#define SleftBraceTagSdouble 158
#define SleftBraceTagSbyteArray 159
#define SrightBraceTagSnull 160
#define SrightBraceTagSinteger 161
#define SrightBraceTagSstring 162
#define SrightBraceTagSexecutableArray 163
#define SrightBraceTagSoperator 164
#define SrightBraceTagSdollar 165
#define SrightBraceTagSarray 166
#define SrightBraceTagSleftBraceTag 167
#define SrightBraceTagSrightBraceTag 168
#define SrightBraceTagSpoly 169
#define SrightBraceTagSarrayOfPOLY 170
#define SrightBraceTagSmatrixOfPOLY 171
#define SrightBraceTagSlist 172
#define SrightBraceTagSfile 173
#define SrightBraceTagSring 174
#define SrightBraceTagSuniversalNumber 175
#define SrightBraceTagSrationalFunction 176
#define SrightBraceTagSclass 177
#define SrightBraceTagSdouble 178
#define SrightBraceTagSbyteArray 179
#define SpolySnull 180
#define SpolySinteger 181
#define SpolySstring 182
#define SpolySexecutableArray 183
#define SpolySoperator 184
#define SpolySdollar 185
#define SpolySarray 186
#define SpolySleftBraceTag 187
#define SpolySrightBraceTag 188
#define SpolySpoly 189
#define SpolySarrayOfPOLY 190
#define SpolySmatrixOfPOLY 191
#define SpolySlist 192
#define SpolySfile 193
#define SpolySring 194
#define SpolySuniversalNumber 195
#define SpolySrationalFunction 196
#define SpolySclass 197
#define SpolySdouble 198
#define SpolySbyteArray 199
#define SarrayOfPOLYSnull 200
#define SarrayOfPOLYSinteger 201
#define SarrayOfPOLYSstring 202
#define SarrayOfPOLYSexecutableArray 203
#define SarrayOfPOLYSoperator 204
#define SarrayOfPOLYSdollar 205
#define SarrayOfPOLYSarray 206
#define SarrayOfPOLYSleftBraceTag 207
#define SarrayOfPOLYSrightBraceTag 208
#define SarrayOfPOLYSpoly 209
#define SarrayOfPOLYSarrayOfPOLY 210
#define SarrayOfPOLYSmatrixOfPOLY 211
#define SarrayOfPOLYSlist 212
#define SarrayOfPOLYSfile 213
#define SarrayOfPOLYSring 214
#define SarrayOfPOLYSuniversalNumber 215
#define SarrayOfPOLYSrationalFunction 216
#define SarrayOfPOLYSclass 217
#define SarrayOfPOLYSdouble 218
#define SarrayOfPOLYSbyteArray 219
#define SmatrixOfPOLYSnull 220
#define SmatrixOfPOLYSinteger 221
#define SmatrixOfPOLYSstring 222
#define SmatrixOfPOLYSexecutableArray 223
#define SmatrixOfPOLYSoperator 224
#define SmatrixOfPOLYSdollar 225
#define SmatrixOfPOLYSarray 226
#define SmatrixOfPOLYSleftBraceTag 227
#define SmatrixOfPOLYSrightBraceTag 228
#define SmatrixOfPOLYSpoly 229
#define SmatrixOfPOLYSarrayOfPOLY 230
#define SmatrixOfPOLYSmatrixOfPOLY 231
#define SmatrixOfPOLYSlist 232
#define SmatrixOfPOLYSfile 233
#define SmatrixOfPOLYSring 234
#define SmatrixOfPOLYSuniversalNumber 235
#define SmatrixOfPOLYSrationalFunction 236
#define SmatrixOfPOLYSclass 237
#define SmatrixOfPOLYSdouble 238
#define SmatrixOfPOLYSbyteArray 239
#define SlistSnull 240
#define SlistSinteger 241
#define SlistSstring 242
#define SlistSexecutableArray 243
#define SlistSoperator 244
#define SlistSdollar 245
#define SlistSarray 246
#define SlistSleftBraceTag 247
#define SlistSrightBraceTag 248
#define SlistSpoly 249
#define SlistSarrayOfPOLY 250
#define SlistSmatrixOfPOLY 251
#define SlistSlist 252
#define SlistSfile 253
#define SlistSring 254
#define SlistSuniversalNumber 255
#define SlistSrationalFunction 256
#define SlistSclass 257
#define SlistSdouble 258
#define SlistSbyteArray 259
#define SfileSnull 260
#define SfileSinteger 261
#define SfileSstring 262
#define SfileSexecutableArray 263
#define SfileSoperator 264
#define SfileSdollar 265
#define SfileSarray 266
#define SfileSleftBraceTag 267
#define SfileSrightBraceTag 268
#define SfileSpoly 269
#define SfileSarrayOfPOLY 270
#define SfileSmatrixOfPOLY 271
#define SfileSlist 272
#define SfileSfile 273
#define SfileSring 274
#define SfileSuniversalNumber 275
#define SfileSrationalFunction 276
#define SfileSclass 277
#define SfileSdouble 278
#define SfileSbyteArray 279
#define SringSnull 280
#define SringSinteger 281
#define SringSstring 282
#define SringSexecutableArray 283
#define SringSoperator 284
#define SringSdollar 285
#define SringSarray 286
#define SringSleftBraceTag 287
#define SringSrightBraceTag 288
#define SringSpoly 289
#define SringSarrayOfPOLY 290
#define SringSmatrixOfPOLY 291
#define SringSlist 292
#define SringSfile 293
#define SringSring 294
#define SringSuniversalNumber 295
#define SringSrationalFunction 296
#define SringSclass 297
#define SringSdouble 298
#define SringSbyteArray 299
#define SuniversalNumberSnull 300
#define SuniversalNumberSinteger 301
#define SuniversalNumberSstring 302
#define SuniversalNumberSexecutableArray 303
#define SuniversalNumberSoperator 304
#define SuniversalNumberSdollar 305
#define SuniversalNumberSarray 306
#define SuniversalNumberSleftBraceTag 307
#define SuniversalNumberSrightBraceTag 308
#define SuniversalNumberSpoly 309
#define SuniversalNumberSarrayOfPOLY 310
#define SuniversalNumberSmatrixOfPOLY 311
#define SuniversalNumberSlist 312
#define SuniversalNumberSfile 313
#define SuniversalNumberSring 314
#define SuniversalNumberSuniversalNumber 315
#define SuniversalNumberSrationalFunction 316
#define SuniversalNumberSclass 317
#define SuniversalNumberSdouble 318
#define SuniversalNumberSbyteArray 319
#define SrationalFunctionSnull 320
#define SrationalFunctionSinteger 321
#define SrationalFunctionSstring 322
#define SrationalFunctionSexecutableArray 323
#define SrationalFunctionSoperator 324
#define SrationalFunctionSdollar 325
#define SrationalFunctionSarray 326
#define SrationalFunctionSleftBraceTag 327
#define SrationalFunctionSrightBraceTag 328
#define SrationalFunctionSpoly 329
#define SrationalFunctionSarrayOfPOLY 330
#define SrationalFunctionSmatrixOfPOLY 331
#define SrationalFunctionSlist 332
#define SrationalFunctionSfile 333
#define SrationalFunctionSring 334
#define SrationalFunctionSuniversalNumber 335
#define SrationalFunctionSrationalFunction 336
#define SrationalFunctionSclass 337
#define SrationalFunctionSdouble 338
#define SrationalFunctionSbyteArray 339
#define SclassSnull 340
#define SclassSinteger 341
#define SclassSstring 342
#define SclassSexecutableArray 343
#define SclassSoperator 344
#define SclassSdollar 345
#define SclassSarray 346
#define SclassSleftBraceTag 347
#define SclassSrightBraceTag 348
#define SclassSpoly 349
#define SclassSarrayOfPOLY 350
#define SclassSmatrixOfPOLY 351
#define SclassSlist 352
#define SclassSfile 353
#define SclassSring 354
#define SclassSuniversalNumber 355
#define SclassSrationalFunction 356
#define SclassSclass 357
#define SclassSdouble 358
#define SclassSbyteArray 359
#define SdoubleSnull 360
#define SdoubleSinteger 361
#define SdoubleSstring 362
#define SdoubleSexecutableArray 363
#define SdoubleSoperator 364
#define SdoubleSdollar 365
#define SdoubleSarray 366
#define SdoubleSleftBraceTag 367
#define SdoubleSrightBraceTag 368
#define SdoubleSpoly 369
#define SdoubleSarrayOfPOLY 370
#define SdoubleSmatrixOfPOLY 371
#define SdoubleSlist 372
#define SdoubleSfile 373
#define SdoubleSring 374
#define SdoubleSuniversalNumber 375
#define SdoubleSrationalFunction 376
#define SdoubleSclass 377
#define SdoubleSdouble 378
#define SdoubleSbyteArray 379
#define SbyteArraySnull 380
#define SbyteArraySinteger 381
#define SbyteArraySstring 382
#define SbyteArraySexecutableArray 383
#define SbyteArraySoperator 384
#define SbyteArraySdollar 385
#define SbyteArraySarray 386
#define SbyteArraySleftBraceTag 387
#define SbyteArraySrightBraceTag 388
#define SbyteArraySpoly 389
#define SbyteArraySarrayOfPOLY 390
#define SbyteArraySmatrixOfPOLY 391
#define SbyteArraySlist 392
#define SbyteArraySfile 393
#define SbyteArraySring 394
#define SbyteArraySuniversalNumber 395
#define SbyteArraySrationalFunction 396
#define SbyteArraySclass 397
#define SbyteArraySdouble 398
#define SbyteArraySbyteArray 399
