#!/bin/sh
# $OpenXM: OpenXM/src/make-links,v 1.5 1999/12/04 02:20:08 takayama Exp $
OpenXM_contrib=../../OpenXM_contrib
OpenXM_contrib2=../../OpenXM_contrib2
/bin/rm -f bin SSkan gmp gc gnuplot ../lib/k097 ../lib/sm1 asir2000 pari
ln -f -s ../bin bin
ln -f -s ./kan96xx SSkan
ln -f -s $OpenXM_contrib/gmp gmp
ln -f -s $OpenXM_contrib/gc gc
ln -f -s $OpenXM_contrib/pari pari
ln -f -s $OpenXM_contrib2/asir2000 asir2000
(cd ../lib ; ln -f -s ../src/k097 k097 ; ln -f -s ../src/kan96xx/Doc sm1)
