.C $OpenXM$
.TH ASIR 1 "20 May 2001"
.SH NAME
asir \-  A general computer algebra system 
.SH SYNOPSIS
.B asir

.SH DESCRIPTION
The system Risa/Asir is a general computer algebra system.
It performs 
.TP
arithmetics in various rings and fields,
factorization, and Groebner basis computations.
.PP
It can call outer modules compliant to the OpenXM protocols.
The asir user language is like C.

.SH USE
.TP
.B quit;
quit asir
.TP
.B load("abc.rr");
Load the file "abc.rr".
.TP
.B help("fctr");
Show a help message for the function "fctr".
.TP


.SH MANUALS
An HTML documentation is available at
.TP
http://www.math.kobe-u.ac.jp/Asir/asir.html
.PP
and at 
.TP
/usr/local/OpenXM/doc/asir
.PP


.SH FILES
.TP
.I asir
main executable,
.I ox_asir
asir server compliant to the OpenXM protocol.
.I lib/asir
library files

.SH PRIMARY FTP SITE
The most recent source distribution from Kobe University can be found at
.RS
.I http://www.math.kobe-u.ac.jp/Asir/asir.html
.RE

As to the OpenXM protocols, see OpenXM home page,
.RS
.I http://www.math.sci.kobe-u.ac.jp/OpenXM 
.RE
or
.RS
.I http://www.openxm.org/kan
.RE


.SH Mails
Questions, comments and bug reports should be sent to
.IR noro@math.kobe-u.ac.jp
Fixes are welcome too !

.SH AUTHOR
Risa/Asir was originally developed at Fujitsu Research Laboratory.
This distribution (Kobe distribution) is patched and maintained by
OpenXM committers.

.SH SEE ALSO
.IR sm1 (1),
.IR M2 (Macaulay 2) (1),
.IR maple (1),
.IR mathematica (1),
.IR openxm (1).

.SH COPYING
Fujitsu Research Laboratory holds the copyright of Risa/Asir.
See the COPYRIGHT file in the source distribution.




