% $OpenXM: OpenXM/src/asir-doc/man.texi,v 1.15 2003/10/19 07:21:57 takayama Exp $
\input texinfo
@iftex
@catcode`@#=6
@def@fref#1{@xrefX[#1,,@code{#1},,,]}
\JP @def@b#1{{@bf@gt #1}}
\EG @def@b#1{{@bf #1}}
@catcode`@#=@other
@end iftex
@overfullrule=0pt
@c -*-texinfo-*-
@comment %**start of header
@setfilename risaman
\JP @documentlanguage ja
@settitle Asir
@comment %**end of header
@comment %@setchapternewpage odd


@ifinfo
@macro fref{name}
\JP @ref{\name\,,@code{\name\}}
\EG @ref{\name\,,@code{\name\}}
@end macro
@end ifinfo

@iftex
@comment @finalout
@end iftex

@titlepage

@title Asir
@subtitle Asir User's Manual
@subtitle Asir-20030424 (Kobe Distribution)
@subtitle April 2003

@author  by Masayuki Noro, Takeshi Shimoyama, Taku Takeshima
@author  and Risa/Asir committers
@page
@vskip 0pt plus 1filll
Copyright @copyright{} FUJITSU LABORATORIES LIMITED.
1994-2000. All rights reserved.
Copyright 2000-2003, Risa/Asir committers, http://www.openxm.org/.
@end titlepage

@synindex vr fn

@comment  node-name,  next,  previous,  up
@node Top,, (dir), (dir)

@menu
* Introduction::
* Risa/Asir::
\BJP
* 型::
* ユーザ言語 Asir::
* デバッガ::
* 組み込み函数::
* 分散計算::
* グレブナ基底の計算::
* 代数的数に関する演算::
* 有限体に関する演算::
* 付録::
* 索引::
\E
\BEG
* Data types::
* User language Asir::
* Debugger::
* Built-in Function::
* Distributed computation::
* Groebner basis computation::
* Algebraic numbers::
* Finite fields::
* Appendix::
* Index::
\E
@end menu

@include parts/intro.texi
@include parts/risa.texi
@include parts/type.texi
@include parts/asir.texi
@include parts/debug.texi
@include parts/builtin.texi
@include parts/process.texi
@include parts/groebner.texi
@include parts/algnum.texi
@include parts/ff.texi
@include parts/appendix.texi

\BJP
@node 索引,,, Top
@unnumbered 索引
\E
\BEG
@node Index,,, Top
@unnumbered Index
\E
@printindex fn
@printindex cp
@iftex
@vfill @eject
@end iftex
@summarycontents
@contents
@bye
