#!/bin/sh
if [ ! `which perl` ]; then
  echo "Perl is not installed. Error: texi2html is aborted."
  exit 1
fi  
if [ -x /usr/bin/texi2html ]; then
  /usr/bin/texi2html $* ;
elif [ -x /usr/local/bin/texi2html ]; then
  /usr/local/bin/texi2html $* ;
else
  echo "Error or Warning: Using OpenXM_HOME in OpenXM/src/asir-doc/texi2html"; perl ${OpenXM_HOME}/src/asir-doc/texi2html.perl $* ;
fi

