# temporary for debug. official one is at ../packages

copy:
	cp intro-ja.html ~/OX4/OpenXM/doc/cfep
	cp ~/OX4/OpenXM/src/asir-contrib/packages/src/cfep-init.rr ~/OX4/OpenXM/lib/asir-contrib
	cp ~/OX4/OpenXM/src/asir-contrib/packages/src/glib3.rr ~/OX4/OpenXM/lib/asir-contrib
